### ISSUE TITLE
`go mod tidy` diff checks should be a part of CI jobs

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/repo-infra#239]
Noticed by @hasheddan in https://github.com/kubernetes/repo-infra/pull/238#pullrequestreview-636184136, I accidentally picked up a go.sum change on a go1.15 branch because my local env is currently running go1.16.3.

Ideally, this should be a CI failure.

**Comment by saschagrunert** [comment]
Updated the labels, I think this is a good first one for @kubernetes/release-engineering

**Comment by palnabarun** [comment]
I can take a look.

/assign

**Comment by palnabarun** [comment]
@justaugustus -- quick query, in https://github.com/kubernetes/repo-infra/pull/238#issuecomment-819940961 you mentioned that you ran `hack/update-deps.sh` with a different Go version. Can you please tell me how did you do that?

I am very new to the Bazel world and couldn't find any satisfactory answer on searching the web or tinkering with the Bazel configs.

**Comment by pravarag** [comment]
Hey @palnabarun , can I work on this  issue if you haven't started already? I'm a bit new to release-engineering and would love to learn a little more by working on this issue 🙂

**Comment by pravarag** [comment]
@palnabarun @justaugustus I've so far understood below points from the requirement of this issue:

1. Add a new CI check (or maybe integrate it with an existing one) which will check for `go mod tidy` output diff. If there is a difference, fail the CI and pass otherwise.
2. If I'm correct, we can add the newer check under this [directory](https://github.com/pravarag/repo-infra/tree/master/verify) as maybe a newer script by name `verify-go-mod-tidy.sh`.
3. Putting this here as an example [verify-vendor](https://github.com/kubernetes/kubernetes/blob/09dc055984e9532f29f37acae7aea7a979ded764/hack/verify-vendor.sh#L68), but the diff check should work something like this?

Kindly let me know if you have any other suggestions on the above points 🙂

**Comment by pravarag** [comment]
@justaugustus @palnabarun I've created a draft PR here: https://github.com/kubernetes/repo-infra/pull/245 and would like to have your suggestions/review comments for making further changes.
